sudo: required
services:
  - docker

before_install:
  - docker build -t eliasabay/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eliasabay/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: frontend
  env: frontend-env
  bucket_name: elasticbeanstalk-us-west-1-274290802243
  bucket_path: docker
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
